//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetTokenAuth_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ShippingAddress { get; set; }
        public string PaymentAmount { get; set; }
        public string OrderStatus { get; set; }
    }
}
